.PHONY: install
install:
	python3 -m pipenv install

.PHONY : q2a
q2a: install
	python3 -m pipenv run q2a

.PHONY : q2b
q2b: install
	python3 -m pipenv run q2b

.PHONY : q2c
q2c: install
	python3 -m pipenv run q2c
